services:
  - type: web
    name: chatwoot-web
    runtime: image
    image:
      url: ghcr.io/chatwoot/chatwoot:latest
    autoDeploy: true
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: NODE_ENV
        value: production
      - key: INSTALLATION_ENV
        value: render
      - key: FRONTEND_URL
        value: "https://chatwoot-web.onrender.com"  # cámbialo luego por tu URL real
      - key: DATABASE_URL
        value: "postgresql://chatwootdb:UhHffcISk9H1Mvja6LrS4it0PN5EktXS@dpg-d3cafd8gjchc7391erp0-a/chatwootdb_w8y7"
      - key: REDIS_URL
        value: "rediss://default:ATTcAAIncDJiY2ZjMjE0ODE3NzU0OGQyODMxZWEyMGIyZTM4YTFjMXAyMTM1MzI@crisp-jaybird-13532.upstash.io:6379"
      - key: SECRET_KEY_BASE
        value: "b926ea5529c267a4da5df97e4eb4ef29"
      # --- SMTP (corrijo user con punto) ---
      - key: MAILER_SENDER_EMAIL
        value: "jcesarap1@gmail.com"
      - key: SMTP_ADDRESS
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_DOMAIN
        value: "gmail.com"
      - key: SMTP_USERNAME
        value: "jcesarap1@gmail.com"
      - key: SMTP_PASSWORD
        value: "busu ramn cemd hmle"
      - key: SMTP_AUTHENTICATION
        value: "plain"
      - key: SMTP_ENABLE_STARTTLS_AUTO
        value: "true"
    # corre migraciones/seeds antes de publicar
    preDeployCommand: "bundle exec rails db:chatwoot_prepare"

  - type: worker
    name: chatwoot-worker
    runtime: image
    image:
      url: ghcr.io/chatwoot/chatwoot:latest
    autoDeploy: true
    envVars:
      - key: WORKER
        value: "1"              # esto hace que la imagen ejecute Sidekiq
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "postgresql://chatwootdb:UhHffcISk9H1Mvja6LrS4it0PN5EktXS@dpg-d3cafd8gjchc7391erp0-a/chatwootdb_w8y7"
      - key: REDIS_URL
        value: "rediss://default:ATTcAAIncDJiY2ZjMjE0ODE3NzU0OGQyODMxZWEyMGIyZTM4YTFjMXAyMTM1MzI@crisp-jaybird-13532.upstash.io:6379"
      - key: SECRET_KEY_BASE
        value: "b926ea5529c267a4da5df97e4eb4ef29"
