services:
  - type: web
    name: chatwoot-web
    runtime: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: NODE_ENV
        value: production
      - key: INSTALLATION_ENV
        value: render
      - key: FRONTEND_URL
        value: "https://<TU_SERVICIO_WEB_CHATWOOT>.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: chatwoot-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: chatwoot-redis
          type: redis
      - key: SECRET_KEY_BASE
        sync: false
      - key: MAILER_SENDER_EMAIL
        sync: false
      - key: SMTP_ADDRESS
        value: "smtp.gmail.com"
      - key: SMTP_DOMAIN
        value: "gmail.com"
      - key: SMTP_ENABLE_STARTTLS_AUTO
        value: "true"
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        sync: false
      # Si usarás S3 para adjuntos, descomenta y completa:
      # - key: ACTIVE_STORAGE_SERVICE
      #   value: amazon
      # - key: AWS_ACCESS_KEY_ID
      #   sync: false
      # - key: AWS_SECRET_ACCESS_KEY
      #   sync: false
      # - key: AWS_REGION
      #   value: us-east-1
      # - key: AWS_BUCKET
      #   value: tu-bucket
    preDeployCommand: "bundle exec rails db:chatwoot_prepare"
    dockerCommand: "bundle exec puma -C config/puma.rb -e production -p ${PORT}"

  - type: worker
    name: chatwoot-worker
    runtime: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: chatwoot-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: chatwoot-redis
          type: redis
      - key: SECRET_KEY_BASE
        sync: false
    dockerCommand: "bundle exec sidekiq -C config/sidekiq.yml"

  - type: redis
    name: chatwoot-redis
    ipAllowList: []   # deja vacío si no quieres restringir IPs

databases:
  - name: chatwoot-postgres
    databaseName: chatwoot
    user: chatwoot
